version: "3.7"
services:
   nginx:
      image: nginx:stable-alpine 
      container_name: nginx
      ports:
      - 80:80 
      volumes:
         - ./backend:/var/www/html/backend #local/container
         - ./backend/default.conf:/etc/nginx/conf.d/default.conf #local/container
      depends_on:
         - backend
         - database
      networks:
         - app
   # nginx:
   #    image: nginx:1.21.5-alpine
   #    container_name: nginx_proxy
   #    ports:
   #       - "80:80"
   #    volumes:
   #       - ./default.conf:/etc/nginx/conf.d/default.conf
   #    networks:
   #       - app
   #    depends_on:
   #       - database
   #       - backend
         #- frontend-angular
   database:
      image: mysql:latest
      container_name: database
      restart: unless-stopped
      tty: true
      ports:
         - "3306:3306"
      command: --default-authentication-plugin=mysql_native_password
      volumes:
         - ./database/sqldump:/docker-entrypoint-initdb.d
         - ./database/conf-search.cnf:/etc/mysql/conf.d/my.cnf
      environment:
         MYSQL_ALLOW_EMPTY_PASSWORD: 1
         MYSQL_DATABASE: "web_movies"
         MYSQL_USER: "admin_webmovies"
         MYSQL_PASSWORD: "123456"
         MYSQL_ROOT_PASSWORD: ""
         SERVICE_TAGS: dev
         SERVICE_NAME: database
      networks:
         app:
   backend:
      build:
         context: ./backend
      ports:
         - "9000:80"
      volumes:
         - './backend:/var/www/html/backend'
         #- './backend/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini'
      #command: sh -c "cd backend && php artisan config:clear && php artisan cache:clear && php artisan view:clear && composer require utrust/utrust --ignore-platform-reqs && php artisan key:generate && php artisan config:cache && php artisan serve"
      depends_on:
         - database
      networks:
         app:
   # frontend-angular:
   #    build:
   #       context: frontend-angular
   #       target: builder
   #    ports:
   #       - 4200:4200
   #    volumes:
   #       - ./frontend-angular:/project
networks:
   app:
